### ISSUE TITLE
Unable to get php7.2-imap

### ISSUE THREAD

**Issue by sdolloffnni** [oerdnj/deb.sury.org#1434]
**Frequently asked questions**

- [X ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
404 Not Found error when trying to install php7.2-imap

**To Reproduce**
1. apt-get install 'php7.2-imap'

Err:1 https://packages.sury.org/php stretch/main amd64 php7.2-imap amd64 7.2.32-1+0~20200710.46+debian9~1.gbp625eb5
  404  Not Found
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-imap_7.2.32-1+0~20200710.46+debian9~1.gbp625eb5_amd64.deb  404  Not Found

**Expected behavior**
The Other php7.2 packages seem to install correctly

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture:  amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php7.2-imap:
  Installed: (none)
  Candidate: 7.2.32-1+0~20200710.46+debian9~1.gbp625eb5
  Version table:
     7.2.32-1+0~20200710.46+debian9~1.gbp625eb5 500
        500 https://packages.sury.org/php stretch/main amd64 Packages

**Additional context**
If I navigate to the URL with a browser, I am able to download the package, but not through apt

**Comment by nojeffrey** [comment]
Also seeing this issue, we're thinking it's Cloudflare related and blocking the user-agent that apt uses, try the following:
    
    apt-get -o Acquire::http::User-Agent=Netscape install php7.2-imap

This seemed to the fix the 404's for me locally, but when running from our datacenter, it still 404's or times out with: 

    curl 'https://packages.sury.org/php/pool/main/p/php7.2/php7.2-common_7.2.32-1+0~20200710.46+debian9~1.gbp625eb5_arm64.deb' --user-agent Netscape -o /tmp/php7.2-common.deb 

So maybe Cloudflare think we're hitting it too much and now we're IP blocked.

**Comment by oerdnj** [comment]
Cloudflare is **not** blocking APT user agent, in fact it is one of the few UA that it doesn't block.

But I will need an IP address related to the blocking, so I can check the logs, I can download the package just fine using apt.

**Comment by thilina-noetic** [comment]
We have got a quite similar kind of issue with a Jenkins server.
` Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-dev_7.3.20-1+0~20200710.65+debian9~1.gbpc9cbeb_amd64.deb  404  Not Found`
`E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-pgsql_7.3.20-1+0~20200710.65+debian9~1.gbpc9cbeb_amd64.deb  404  Not Found`

**Comment by ixa-devstuff** [comment]
My office has had this issue all day from our CI server but from my local machine in another state, I have no issue building Docker container and installing.

is there any guide on how to use the rsync information I found related to this issue
`apt-get download php7.2-cli` 
I would very much like to understand who this method would be used

[https://www.patreon.com/posts/use-rsync-luke-32563640](https://www.patreon.com/posts/use-rsync-luke-32563640)

I can access the package .deb files but installing is a problem I have not been able to solve.

**Comment by lpiob** [comment]
Debian 9.12 Stretch, IP: 34.243.67.147

```# apt-get install php7.3-pgsql
Reading package lists... Done
[...]
Do you want to continue? [Y/n] y
Err:1 https://packages.sury.org/php stretch/main amd64 php7.3-pgsql amd64 7.3.20-1+0~20200710.65+debian9~1.gbpc9cbeb
  404  Not Found
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-pgsql_7.3.20-1+0~20200710.65+debian9~1.gbpc9cbeb_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?```

Time: 12:48:49 UTC

**Comment by sdolloffnni** [comment]
> Cloudflare is **not** blocking APT user agent, in fact it is one of the few UA that it doesn't block.
> 
> But I will need an IP address related to the blocking, so I can check the logs, I can download the package just fine using apt.

34.205.160.22

**Comment by oerdnj** [comment]
> 34.205.160.22

There are no records neither in the CF firewall log nor on the server, the last entry I see on the server is this:

`34.205.160.22 - - [13/Jul/2020:23:48:01 +0000] "GET /php/pool/main/p/php-uuid/php-uuid_1.1.0-1%2b0%7e20191219.9%2bdebian9%7e1.gbp98f5ee_amd64.deb HTTP/1.1" 200 8724 "-" "Debian APT-CURL/1.0 (1.4.10)"`

Is it possible there's a (transparent) proxy in between you and the server?

**Comment by oerdnj** [comment]
> 34.243.67.147

There's one blocked access to `php7.3-pgsql_7.3.20-1+0~20200710.65+debian9~1.gbpc9cbeb_amd64.deb` using wget and no access in the nginx access.log.

**Comment by rfay** [comment]
I see lots of php7.2 blocked, php7.2-zip is listed here as an example, although there are lots of packages that *don't* get blocked. This is on a fresh Debian 10 which never had deb.sury.org on it before.  I am able to install php7.3-zip, php7.0-zip, php7.1-zip, php7.4-zip successfully. But php7.2-zip gets a 404. 

IP address: 69.146.74.18

```
$ sudo apt-get install --fix-missing php7.2-zip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libzip4 php-common php7.2-common
The following NEW packages will be installed:
  libzip4 php-common php7.2-common php7.2-zip
0 upgraded, 4 newly installed, 0 to remove and 9 not upgraded.
Need to get 587 kB/654 kB of archives.
After this operation, 6,650 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 https://packages.sury.org/php buster/main amd64 php7.2-common amd64 7.2.32-1+0~20200710.46+debian10~1.gbp625eb5
  404  Not Found [IP: 172.67.182.150 443]
Err:2 https://packages.sury.org/php buster/main amd64 php7.2-zip amd64 7.2.32-1+0~20200710.46+debian10~1.gbp625eb5
  404  Not Found [IP: 172.67.182.150 443]
Unable to correct missing packages.
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-common_7.2.32-1+0~20200710.46+debian10~1.gbp625eb5_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-zip_7.2.32-1+0~20200710.46+debian10~1.gbp625eb5_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Aborting install.
```

**Comment by oerdnj** [comment]
I flushed the cache again. Perhaps something went wrong and the 404 got cached at some cache end points.

**Comment by rfay** [comment]
I am now able to install php7.2-zip, thanks.

**Comment by oerdnj** [comment]
Ok, so it seems that some CF nodes has cached the 404 somewhere for who-know-reason and that got replayed to the end servers. Can anyone else confirm that this has been solved for them?

**Comment by lpiob** [comment]
I can confirm that I am now able to download packages successfully.

**Comment by nirodaonline** [comment]
Hi,

It's still happening to me for 3 packages - php7.2-imap php7.2-sqlite3 php7.2-tidy:

```
$ sudo apt-get install php7.2-imap php7.2-sqlite3 php7.2-tidy --fix-missing
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  php7.2-imap php7.2-sqlite3 php7.2-tidy
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 73.3 kB of archives.
After this operation, 341 kB of additional disk space will be used.
Err:1 https://packages.sury.org/php buster/main amd64 php7.2-imap amd64 7.2.34-10+0~20210209.54+debian10~1.gbpc2b67f
  404  Not Found [IP: 172.67.182.150 443]
Err:2 https://packages.sury.org/php buster/main amd64 php7.2-sqlite3 amd64 7.2.34-10+0~20210209.54+debian10~1.gbpc2b67f
  404  Not Found [IP: 172.67.182.150 443]
Err:3 https://packages.sury.org/php buster/main amd64 php7.2-tidy amd64 7.2.34-10+0~20210209.54+debian10~1.gbpc2b67f
  404  Not Found [IP: 172.67.182.150 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-imap_7.2.34-10+0~20210209.54+debian10~1.gbpc2b67f_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-sqlite3_7.2.34-10+0~20210209.54+debian10~1.gbpc2b67f_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-tidy_7.2.34-10+0~20210209.54+debian10~1.gbpc2b67f_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Internal Error, ordering was unable to handle the media swap
```
IP: 194.158.18.3

Could it be the cache again?

Thanks

**Comment by spanner28** [comment]
Hi, I know this issue has been closed but I'm experiencing the issue now:
```bash
apt-get install php7.4-imap
```

```bash
Do you want to continue? [Y/n] Y
Err:1 https://packages.sury.org/php buster/main amd64 php7.4-imap amd64 7.4.14-1+0~20210112.34+debian10~1.gbpaa175a
  404  Not Found [IP: 172.67.182.150 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-imap_7.4.14-1+0~20210112.34+debian10~1.gbpaa175a_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Can you please confirm @oerdnj
