### ISSUE TITLE
readline for PHP 7.0

### ISSUE THREAD

**Issue by dlussky** [oerdnj/deb.sury.org#158]
It would be wonderful to have it, because psysh is relying on that (it works without,  but you don't have any cool navigation support)

Thanks!

**Comment by oerdnj** [comment]
fixed in php7.0_7.0.0-5+deb.sury.org~<dist>+1

**Comment by dlussky** [comment]
Thanks)

**Comment by jadjoubran** [comment]
Hi @oerdnj 
Thanks for your hard work.

I updated to PHP 7.0.0-5+deb.sury.org~trusty+1 (cli) ( NTS )
And readline is still not enabled. Is there a way to enable it?
Thanks

**Comment by oerdnj** [comment]
Did you install php7.0-readline 

On 12 Dec 2015, Jad Joubran <notifications@github.com> wrote:
>Hi @oerdnj 
>Thanks for your hard work.
>
>I updated to PHP 7.0.0-5+deb.sury.org~trusty+1 (cli) ( NTS )
>And readline is still not enabled. Is there a way to enable it?
>Thanks
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/158#issuecomment-164168214

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by jadjoubran** [comment]
Got it, thanks a lot @oerdnj :smile:
