### ISSUE TITLE
PECL extension packages missing the .so after update

### ISSUE THREAD

**Issue by j-engel** [oerdnj/deb.sury.org#1676]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
after last apt update all imagick.so files are missing from the /usr/lib/php/.../ folders

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/imagick.so' - /usr/lib/php/20131226/imagick.so: cannot open shared object file: No such file or directory in Unknown on line 0

The file is indeed missing - and i can see in the backups that it was there before the apt upgrade

From /var/log/apt/history.log:
Start-Date: 2021-11-10  13:29:01
Commandline: apt dist-upgrade
Upgrade: php7.2-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php7.1-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php7.4-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php7.3-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php8.1-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php8.0-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php5.6-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php7.0-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1), php-imagick:amd64 (3.5.1-1+ubuntu18.04.1+deb.sury.org+2, 3.5.1-2+ubuntu18.04.1+deb.sury.org+1)
End-Date: 2021-11-10  13:29:13

**To Reproduce**
sudo apt update
sudo apt upgrade
php -m

**Expected behavior**
imagick.so should be in the /usr/lib/php/.../ - folder

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Architecture: amd64
 - Repository: http://ppa.launchpad.net/ondrej/php/ubuntu bionic main

**Package(s) (please complete the following information):**
php-imagick:
  Installed: 3.5.1-2+ubuntu18.04.1+deb.sury.org+1
  Candidate: 3.5.1-2+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 3.5.1-2+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.4.3~rc2-2ubuntu4.1 500
        500 http://mirror.hetzner.de/ubuntu/packages bionic-security/universe amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages bionic-updates/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
     3.4.3~rc2-2ubuntu4 500
        500 http://mirror.hetzner.de/ubuntu/packages bionic/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

php5.6-imagick:
  Installed: 3.5.1-2+ubuntu18.04.1+deb.sury.org+1
  Candidate: 3.5.1-2+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 3.5.1-2+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by JB1985** [comment]
Same here with memcached and redis on debian 10.

PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib/php/20210902/imagick.so (/usr/lib/php/20210902/imagick.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/imagick.so.so (/usr/lib/php/20210902/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20210902/redis.so (/usr/lib/php/20210902/redis.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/redis.so.so (/usr/lib/php/20210902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20210902/memcached.so (/usr/lib/php/20210902/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/memcached.so.so (/usr/lib/php/20210902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by oerdnj** [comment]
Seems like some glitch that didn't happen locally with new `dh-php` helper.  I'm looking into it.

**Comment by sdrycroft** [comment]
I'm not sure if this is of any help.

```bash
# dpkg -L php7.4-imagick
/.
/etc
/etc/php
/etc/php/7.4
/etc/php/7.4/mods-available
/etc/php/7.4/mods-available/imagick.ini
/usr
/usr/share
/usr/share/doc
/usr/share/doc/php7.4-imagick
/usr/share/doc/php7.4-imagick/changelog.Debian.gz
/usr/share/doc/php7.4-imagick/copyright
```
```bash
# dpkg -L php-imagick
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/php-imagick
/usr/share/doc/php-imagick/changelog.Debian.gz
/usr/share/doc/php-imagick/copyright
```
```bash
# apt-file search imagick.so
php-imagick: /usr/lib/php/20170718/imagick.so
```
```bash
# ls -l /usr/lib/php/
total 52
drwxr-xr-x 3 root root 4096 Nov 10 13:23 20190902
drwxr-xr-x 2 root root 4096 Nov 10 13:31 20210902
drwxr-xr-x 3 root root 4096 Nov 10 13:23 7.4
drwxr-xr-x 2 root root 4096 Nov 10 13:31 8.1
-rw-r--r-- 1 root root   13 Nov  4 13:57 packaging
-rwxr-xr-x 1 root root  309 Oct 22 12:33 php7.4-fpm-reopenlogs
-rwxr-xr-x 1 root root  514 Nov  4 13:57 php-fpm-socket-helper
-rw-r--r-- 1 root root 4845 Nov  4 13:57 php-helper
-rw-r--r-- 1 root root 9234 Nov  4 13:57 php-maintscript-helper
-rwxr-xr-x 1 root root 2976 Nov  4 13:57 sessionclean
```
```bash
# dpkg -l | grep php
ii  dh-php                                 4.1+ubuntu18.04.1+deb.sury.org+1                                    all          debhelper add-on to handle PHP PECL extensions
ii  php-apcu-bc                            1.0.5-14+ubuntu18.04.1+deb.sury.org+1                               amd64        APCu Backwards Compatibility Module
ii  php-common                             2:85+ubuntu18.04.1+deb.sury.org+1                                   all          Common files for PHP packages
ii  php-imagick                            3.5.1-2+ubuntu18.04.1+deb.sury.org+1                                amd64        Provides a wrapper to the ImageMagick library
ii  php-pear                               1:1.10.12+submodules+notgz+20210212-1+ubuntu18.04.1+deb.sury.org+1  all          PEAR Base System
ii  php7.4                                 7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.4-apcu                            5.1.21+4.0.11-2+ubuntu18.04.1+deb.sury.org+1                        amd64        APC User Cache for PHP
ii  php7.4-apcu-bc                         1.0.5-14+ubuntu18.04.1+deb.sury.org+1                               amd64        APCu Backwards Compatibility Module
ii  php7.4-cli                             7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        command-line interpreter for the PHP scripting language
ii  php7.4-common                          7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        documentation, examples and common module for PHP
ii  php7.4-curl                            7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        CURL module for PHP
ii  php7.4-dev                             7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        Files for PHP7.4 module development
ii  php7.4-fpm                             7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.4-gd                              7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        GD module for PHP
ii  php7.4-igbinary                        3.2.6+2.0.8-2+ubuntu18.04.1+deb.sury.org+1                          amd64        igbinary PHP serializer
ii  php7.4-imagick                         3.5.1-2+ubuntu18.04.1+deb.sury.org+1                                amd64        Provides a wrapper to the ImageMagick library
ii  php7.4-intl                            7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        Internationalisation module for PHP
ii  php7.4-json                            7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        JSON module for PHP
ii  php7.4-mbstring                        7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        MBSTRING module for PHP
ii  php7.4-memcache                        8.0+4.0.5.2+3.0.9~20170802.e702b5f9+-3+ubuntu18.04.1+deb.sury.org+1 amd64        memcache extension module for PHP
ii  php7.4-memcached                       3.1.5+2.2.0-10+ubuntu18.04.1+deb.sury.org+1                         amd64        memcached extension module for PHP, uses libmemcached
ii  php7.4-msgpack                         2.2.0~rc1+2.1.2+0.5.7-2+ubuntu18.04.1+deb.sury.org+1                amd64        PHP extension for interfacing with MessagePack
ii  php7.4-mysql                           7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        MySQL module for PHP
ii  php7.4-opcache                         7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        Zend OpCache module for PHP
ii  php7.4-pcov                            1.0.9-2+ubuntu18.04.1+deb.sury.org+1                                amd64        Code coverage driver
ii  php7.4-readline                        7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        readline module for PHP
ii  php7.4-soap                            7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        SOAP module for PHP
ii  php7.4-xdebug                          3.1.1+2.9.8+2.8.1+2.5.5-2+ubuntu18.04.1+deb.sury.org+1              amd64        Xdebug Module for PHP
ii  php7.4-xml                             7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        DOM, SimpleXML, XML, and XSL module for PHP
ii  php7.4-zip                             7.4.25-1+ubuntu18.04.1+deb.sury.org+1                               amd64        Zip module for PHP
ii  php8.1-common                          8.1.0~rc5-2+ubuntu18.04.1+deb.sury.org+1                            amd64        documentation, examples and common module for PHP
ii  php8.1-imagick                         3.5.1-2+ubuntu18.04.1+deb.sury.org+1                                amd64        Provides a wrapper to the ImageMagick library
ii  pkg-php-tools                          1.35ubuntu1                                                         all          various packaging tools and scripts for PHP packages
```

**Comment by JB1985** [comment]
After I install a new update for php-igbinary & php-msgpack I get more errors:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary.so' (tried: /usr/lib/php/20190902/igbinary.so (/usr/lib/php/20190902/igbinary.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/igbinary.so.so (/usr/lib/php/20190902/igbinary.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib/php/20190902/imagick.so (/usr/lib/php/20190902/imagick.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/imagick.so.so (/usr/lib/php/20190902/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'msgpack.so' (tried: /usr/lib/php/20190902/msgpack.so (/usr/lib/php/20190902/msgpack.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/msgpack.so.so (/usr/lib/php/20190902/msgpack.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/redis.so.so (/usr/lib/php/20190902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20190902/memcached.so (/usr/lib/php/20190902/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcached.so.so (/usr/lib/php/20190902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by oerdnj** [comment]
I see that, I just don't know why is this happening, because locally the `debuild` puts everything into right places.

**Comment by sdrycroft** [comment]
```# dh_php --php-version=7.4
dh_php: "debian/control" not found. Are you sure you are in the correct directory?
```

**Comment by j-engel** [comment]
> 
> 
> Same here with memcached and redis on debian 10.
> 
> ```
> PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib/php/20210902/imagick.so (/usr/lib/php/20210902/imagick.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/imagick.so.so (/usr/lib/php/20210902/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
> PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20210902/redis.so (/usr/lib/php/20210902/redis.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/redis.so.so (/usr/lib/php/20210902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
> PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20210902/memcached.so (/usr/lib/php/20210902/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/memcached.so.so (/usr/lib/php/20210902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
> ```
> 
> ```
> ii  php-redis                            5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> rc  php5.6-redis                         5.3.4+4.3.0-1+0~20210329.35+debian10~1.gbpdc7ead                         amd64        PHP extension for interfacing with Redis
> ii  php7.0-redis                         5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> ii  php7.1-redis                         5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> ii  php7.2-redis                         5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> ii  php7.3-redis                         5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> ii  php7.4-redis                         5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> ii  php8.0-redis                         5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> ii  php8.1-redis                         5.3.4+4.3.0-5+0~20211110.36+debian10~1.gbpf06028                         amd64        PHP extension for interfacing with Redis
> ```
> 
> ```
> ii  memcached                            1.5.6-1.1                                                                amd64        high-performance memory object caching system
> ii  php-memcached                        3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> rc  php5.6-memcached                     3.1.5+2.2.0-9+0~20210228.30+debian10~1.gbp2db493                         amd64        memcached extension module for PHP, uses libmemcached
> ii  php7.0-memcached                     3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> ii  php7.1-memcached                     3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> ii  php7.2-memcached                     3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> ii  php7.3-memcached                     3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> ii  php7.4-memcached                     3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> ii  php8.0-memcached                     3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> ii  php8.1-memcached                     3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf                        amd64        memcached extension module for PHP, uses libmemcached
> ```
> 
> ```
> ii  php-imagick                          3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> rc  php5.6-imagick                       3.4.4+php8.0+3.4.4-7+0~20210305.28+debian10~1.gbpdcb27b                  amd64        Provides a wrapper to the ImageMagick library
> ii  php7.0-imagick                       3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> ii  php7.1-imagick                       3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> ii  php7.2-imagick                       3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> ii  php7.3-imagick                       3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> ii  php7.4-imagick                       3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> ii  php8.0-imagick                       3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> ii  php8.1-imagick                       3.5.1-2+0~20211110.31+debian10~1.gbp94a5d6                               amd64        Provides a wrapper to the ImageMagick library
> ```

**Comment by j-engel** [comment]
sorry... hit the wrong button

**Comment by werk21** [comment]
Same for

- apcu.so
- igbinary.so
- mcrypt.so
- msgpack.so

Thank you for your work!

Notice: While updating apt removed  libmcrypt4 and libmemcached11:amd64.

**Comment by pyaillet** [comment]
I can confirm the same problem and additional packages concerned:
- memcached.so
- grpc.so
- protobuf.so

**Comment by galibozek** [comment]
I can confirm the same problem for: gearman.so

**Comment by richardfelkl** [comment]
same problem here

**Comment by abed19919** [comment]
Same here with **mongodb.so**

**Comment by stefarossi** [comment]
I'm having the same problem with apcu, mongodb and geoip

**Comment by bognerf** [comment]
Can confirm this behaviour after `apt upgrade` with Ubuntu 18.04 and PHP7.3

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary.so' (tried: /usr/lib/php/20180731/igbinary.so (/usr/lib/php/20180731/igbinary.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/igbinary.so.so (/usr/lib/php/20180731/igbinary.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20180731/redis.so (/usr/lib/php/20180731/redis.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/redis.so.so (/usr/lib/php/20180731/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.3.31-2+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 22 2021 12:34:00) ( NTS )

```

**Comment by piotrooo** [comment]
Same here. Related with:
* apcu.so
* gearman.so
* memcached.so

**Comment by oerdnj** [comment]
If you are running Ubuntu, could you try installing apcu from here? And report back...

https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/22392441

**Comment by sdrycroft** [comment]
Appears to have worked...

```bash
$ sudo dpkg -i php7.4-apcu_5.1.21+4.0.11-2+ubuntu21.10.1+deb.sury.org+2_amd64.deb 
(Reading database ... 126889 files and directories currently installed.)
Preparing to unpack php7.4-apcu_5.1.21+4.0.11-2+ubuntu21.10.1+deb.sury.org+2_amd64.deb ...
Unpacking php7.4-apcu (5.1.21+4.0.11-2+ubuntu21.10.1+deb.sury.org+2) over (5.1.21+4.0.11-2+ubuntu18.04.1+deb.sury.org+1) ...
dpkg: dependency problems prevent configuration of php7.4-apcu:
 php7.4-apcu depends on libc6 (>= 2.34); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.4.

dpkg: error processing package php7.4-apcu (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 php7.4-apcu
vagrant@dev-fundraising:/var/www/cruk_fundraising_web_service$ php --version
PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary.so' (tried: /usr/lib/php/20190902/igbinary.so (/usr/lib/php/20190902/igbinary.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/igbinary.so.so (/usr/lib/php/20190902/igbinary.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib/php/20190902/imagick.so (/usr/lib/php/20190902/imagick.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/imagick.so.so (/usr/lib/php/20190902/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcache.so' (tried: /usr/lib/php/20190902/memcache.so (/usr/lib/php/20190902/memcache.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcache.so.so (/usr/lib/php/20190902/memcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'msgpack.so' (tried: /usr/lib/php/20190902/msgpack.so (/usr/lib/php/20190902/msgpack.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/msgpack.so.so (/usr/lib/php/20190902/msgpack.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pcov.so' (tried: /usr/lib/php/20190902/pcov.so (/usr/lib/php/20190902/pcov.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/pcov.so.so (/usr/lib/php/20190902/pcov.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'apc.so' (tried: /usr/lib/php/20190902/apc.so (/usr/lib/php/20190902/apc.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/apc.so.so (/usr/lib/php/20190902/apc.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20190902/memcached.so (/usr/lib/php/20190902/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcached.so.so (/usr/lib/php/20190902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.4.25 (cli) (built: Oct 22 2021 12:33:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
```

**Comment by kayamaty** [comment]
Same here. Missing

- apcu.so
- igbinary.so
- imagick.so
- apc.so

for all PHP-Versions from 7.2 to 8.1

**Comment by werk21** [comment]
I installed php7.2-apcu_5.1.21+4.0.11-2+ubuntu18.04.1+deb.sury.org+3_amd64.deb and it looks good!

`-rw-r--r-- 1 root root   75880 Nov 10 15:39 apcu.so`

thank you!

**Comment by mabihan** [comment]
Here I get the same problem @sdrycroft  : 

```
~# sudo dpkg -i php7.3-apcu_5.1.21+4.0.11-2+ubuntu21.10.1+deb.sury.org+2_amd64.deb
Sélection du paquet php7.3-apcu précédemment désélectionné.
(Lecture de la base de données... 109420 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de php7.3-apcu_5.1.21+4.0.11-2+ubuntu21.10.1+deb.sury.org+2_amd64.deb ...
Dépaquetage de php7.3-apcu (5.1.21+4.0.11-2+ubuntu21.10.1+deb.sury.org+2) ...
dpkg: des problèmes de dépendances empêchent la configuration de php7.3-apcu :
 php7.3-apcu dépend de libc6 (>= 2.34) ; cependant :
  La version de libc6:amd64 sur le système est 2.27-3ubuntu1.4.

dpkg: erreur de traitement du paquet php7.3-apcu (--install) :
 problèmes de dépendances - laissé non configuré
Des erreurs ont été rencontrées pendant l'exécution :
 php7.3-apcu
```

**Comment by lawli3t** [comment]
Can confirm with

imagick
mcrypt
xdebug

on 18.04 - PHP all version

**Comment by jpjones** [comment]
Same issue for ampq.so - Ubuntu 18.08, PHP and PHP7.4

**Comment by tersmitten** [comment]
Same here:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary.so' (tried: /usr/lib/php/20190902/igbinary.so (/usr/lib/php/20190902/igbinary.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/igbinary.so.so (/usr/lib/php/20190902/igbinary.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcache.so' (tried: /usr/lib/php/20190902/memcache.so (/usr/lib/php/20190902/memcache.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcache.so.so (/usr/lib/php/20190902/memcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'msgpack.so' (tried: /usr/lib/php/20190902/msgpack.so (/usr/lib/php/20190902/msgpack.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/msgpack.so.so (/usr/lib/php/20190902/msgpack.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20190902/memcached.so (/usr/lib/php/20190902/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcached.so.so (/usr/lib/php/20190902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

Ubuntu 18.08, PHP 7.4

**Comment by JimmyBanks** [comment]
Can confirm with:

imagick
igbinary
redis

Ubuntu 18.04, PHP 8.0

**Comment by oerdnj** [comment]
> @oerdnj I installed the new bionic package php7.2-apcu_5.1.21+4.0.11-2+ubuntu18.04.1+deb.sury.org+3_amd64.deb and it looks good!
> 
> 
> 
> `-rw-r--r-- 1 root root   75880 Nov 10 15:39 apcu.so`
> 
> 
> 
> See https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/22392498
> 
> 
> 
> thank you!

Thanks for the confirmation.  I scheduled rebuild of all the extensions.

**Comment by JakeBooher** [comment]
Was having the issue with igbinary.so, and several others. Have ran an apt upgrade after seeing this issue and most went away, still getting one for memcached though:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20190902/memcached.so (/usr/lib/php/20190902/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcached.so.so (/usr/lib/php/20190902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by drAlberT** [comment]
`redis.so`  on php7.4 too

**Comment by kromonos** [comment]
Same problem with following modules on Debian 8 with PHP 5.6 up to 7.4 as FPM:
* mailparse.so
* memcached.so
* protobuf.so
* zstd.so
* yaml.so
* uuid.so
* uploadprogress.so
* stomp.so
* ssh2.so
* smbclient.so
* rrd.so
* redis.so
* raphf.so
* radius.so
* propro.so
* msgpack.so
* mcrypt.so
* imagick.so
* igbinary.so
* apcu.so

**Comment by kromonos** [comment]
Bullseye packages seems to be ok:
![image](https://user-images.githubusercontent.com/1553902/141151519-bce35637-3a9a-48d1-bfd8-3b51e1478c81.png)

**Comment by mgascoyne** [comment]
@oerdnj Same issues here with various extensions. I've looked at the PPA page on https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages and see that the PPA repository is almost full:

Repository size:
23.2 GiB (96.80%) of 24.0 GiB

Could that possibly the problem ?

Thx,
Marcel

**Comment by BrynM** [comment]
I think you may be onto something @mgascoyne. As things are getting rebuilt, the limit keeps getting bumped into.

```
Repository size:
24.7 GiB (100.00%) of 24.0 GiB
```

**Comment by danielb42** [comment]
The `ondrej/php/ubuntu` ppa seems to have received fixed packages. I did nothing else to my system (the broke earlier today after updating) and the updates to `php7.4-apcu php7.4-igbinary php7.4-imagick` that just came in fixed the problems.

**Comment by gabrielspiteri-highlight** [comment]
Just wanted to add that we are using debian stretch with php 7.4 and it would seem that raphf, propro and apc are effected:

PHP Warning:  PHP Startup: Unable to load dynamic library 'propro.so' 
PHP Warning:  PHP Startup: Unable to load dynamic library 'raphf.so' 
PHP Warning:  PHP Startup: Unable to load dynamic library 'apc.so' 

Thanks for your work :) we await updated packages

**Comment by MarkG-IEL** [comment]
@oerdnj Looks like a few popular extensions failed to build:
php-redis - 5.3.4+4.3.0-5+ubuntu18.04.1+deb.sury.org+3
php-memcached - 3.1.5+2.2.0-10+ubuntu18.04.1+deb.sury.org+3

Looks like a build failure on one arch is preventing the publishing of the update on any arch. A few other minor extensions failing, but these are two that I figure lots of people use (including me!)

**Comment by deedup-daw** [comment]
I had the same issue on Debian 10 buster. Encountered the problem with imagick, ssh2, yaml, mcrypt

I don't know if something was recently fixed, but on some systems, I just ran "apt-get upgrade; apt-get dist-upgrade" resolved the issue.

For the one system this didn't work on, I ran "apt-get remove php-yaml php7.4-yaml; apt autoremove; apt-get install php-yaml" and that fixed the issue on that system.

**Comment by oerdnj** [comment]
igbinary needs working apcu, memcached needs msgpack and igbinary, redis needs igbinary...

Or something like that.  It will require bit of manual intervention.

**Comment by JB1985** [comment]
The new packages are currently being built. It can take a while until all packages are ready. Just be patient.

The only thing missing is php memcached. There are new packages for everything else.

**Comment by MarkG-IEL** [comment]
> igbinary needs working apcu, memcached needs msgpack and igbinary, redis needs igbinary...
> 
> Or something like that. It will require bit of manual intervention.

Thanks for the update. apcu looks to have run fine, so hopefully a rebuild is all that's needed.

**Comment by tersmitten** [comment]
Patiently waiting for `php-memcached`. "The others" are fixed for us.

**Comment by BrynM** [comment]
Still having issues with 7.1 packages on bionic. Lots of failed amd64 builds at https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic

**Comment by gabrielspiteri-highlight** [comment]
Confirming apcu and propro looks ok ... however raphf still seems missing the .so file

**Comment by JimmyBanks** [comment]
The builds have completed; however, there were build failures.

Redis was one of them, and the "Redis.so" bug is still persisting.

**Comment by JB1985** [comment]
@oerdnj can there be problems building the php-memcached package for debian? I'm just not getting an update.

All other packages are fine.

Sorry, now I'm impatient.

**Comment by oerdnj** [comment]
You can monitor the restarted memcached rebuild here: https://jenkins.rfc1925.org/job/php_php-memcached-binaries/37/

**Comment by oerdnj** [comment]
The Debian build server is a busy bee right now:
```
 19:33:41 up 5 days,  1:35,  3 users,  load average: 29.28, 31.41, 23.74
```

**Comment by BrynM** [comment]
Confirmed redis and memcached builds fixed for 7.1/bionic. We still have apc left to go, but I'm willing to be patient. Thank you @oerdnj!

**Comment by oerdnj** [comment]
Bionic apcu-bc is almost done now: https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/22392481

**Comment by oerdnj** [comment]
The Debian build infrastructure is bit more fragile than launchpad, so it might take few more reschedules to fix the non-amd64 builds.

Who would have thought that generating `debian/control` in a different step would have such an impact. Especially when you everything was just fine when built with `debuild` locally.  I moved the `debian/control` back as pre-dependency to `dh_prep` step and everything works fine again.  I guess some `dh` magic caused this.

Does anybody know whether `bullseye` was also affected?

**Comment by BrynM** [comment]
All good on my end now. Thanks again. Unfortunately I don't have any Debian info for you. Good luck!

**Comment by pyaillet** [comment]
All good on `buster` 👍 
Thank you :)

No info on `bullseye` either :\

**Comment by kromonos** [comment]
> All good on `buster` +1 Thank you :)
> 
> No info on `bullseye` either :\

Bullseye info here: https://github.com/oerdnj/deb.sury.org/issues/1676#issuecomment-965507031

**Comment by oerdnj** [comment]
> > All good on `buster` +1 Thank you :)
> > No info on `bullseye` either :\
> 
> Bullseye info here: [#1676 (comment)](https://github.com/oerdnj/deb.sury.org/issues/1676#issuecomment-965507031)

Thanks. So, that's probably the difference why I didn't catch this before everything went to the hellhole. My primary system is Debian bullseye and it doesn't seem to be affected.

**Comment by kromonos** [comment]
> Thanks. So, that's probably the difference why I didn't catch this before everything went to the hellhole. My primary system is Debian bullseye and it doesn't seem to be affected.

Exactly. After I switched on my system from buster to bullseye and made a `apt upgrade` the problem was gone for me too.

**Comment by tersmitten** [comment]
Thanks @oerdnj for saving the day. All my machines are back to normal again.

**Comment by gabrielspiteri-highlight** [comment]
@oerdnj we are still getting error saying PHP Startup: Unable to load dynamic library 'raphf.so' (tried: /usr/lib/php/20190902/raphf.so ... this is within a debian:stretch docker container. Just checking if we need to still wait for fresh builds?

**Comment by oerdnj** [comment]
> @oerdnj we are still getting error saying PHP Startup: Unable to load dynamic library 'raphf.so' (tried: /usr/lib/php/20190902/raphf.so ... this is within a debian:stretch docker container. Just checking if we need to still wait for fresh builds?

Architecture?

**Comment by mgascoyne** [comment]
At least the xdebug.so extension is still missing on amd64 / Ubuntu 18.04 bionic.

**Comment by oerdnj** [comment]
Yeah, with impish in place I've hit the repository size limits again.  Hopefully, someone from Canonical will bump the limits during the day, so I can upload to the PPA again.

**Comment by gabrielspiteri-highlight** [comment]
> > @oerdnj we are still getting error saying PHP Startup: Unable to load dynamic library 'raphf.so' (tried: /usr/lib/php/20190902/raphf.so ... this is within a debian:stretch docker container. Just checking if we need to still wait for fresh builds?
> 
> Architecture?

@oerdnj amd64 ... but now its all good thanks again!

**Comment by oerdnj** [comment]
I think everything should be in order now more or less. The Debian arm packages are still building, but they are fringe, so I am closing this for now.
