### ISSUE TITLE
Several apr libs missing

### ISSUE THREAD

**Issue by fretb** [oerdnj/deb.sury.org#2269]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
Hello @oerdnj, as always, let me begin by thanking you for all your hard work!

I noticed that since recently, there seem to be some libapr* builds missing in the current repository.

On Debian Bookworm amd64:
```
The following packages have unmet dependencies:
 libapr1t64 : Breaks: libapr1 (< 1.7.5-1+0~20250309.2+debian12~1.gbp3e4826) but 1.7.2-3+deb12u1 is to be installed
 libaprutil1t64 : Breaks: libaprutil1 (< 1.6.3-3+0~20250309.4+debian12~1.gbp0e3dab) but 1.6.3-1+0~20250308.1+debian12~1.gbpc0b512 is to be installed
```

If I look in the repository, I indeed so older builds active for `libapr1` and `libaprutil1`:

- https://packages.sury.org/apache2/pool/main/a/apr/libapr1_1.7.2-2%2B0~20250308.1%2Bdebian12~1.gbpacc583_amd64.deb
- https://packages.sury.org/apache2/pool/main/a/apr-util/libaprutil1_1.6.3-1%2B0~20250308.1%2Bdebian12~1.gbpc0b512_amd64.deb

Maybe something went wrong during the release of the latest builds?

**Comment by mishal** [comment]
I have the same/similar issue, while trying to install modsecurity2 (on Debian Bullseye):

```
$ sudo apt install libapache2-mod-security2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libapr1t64 : Breaks: libapr1 (< 1.7.5-1+0~20250309.2+debian11~1.gbp3e4826) but 1.7.2-2+0~20250308.1+debian11~1.gbpacc583 is to be installed
 libaprutil1t64 : Breaks: libaprutil1 (< 1.6.3-3+0~20250309.4+debian11~1.gbp0e3dab) but 1.6.3-1+0~20250308.1+debian11~1.gbpc0b512 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by oerdnj** [comment]
Thanks for noticing this. I’m in the process of updating the repositories for Trixie and it seems it will be messy because of the 64-bit transition. I’ll fix this later in the day. It needs two different versions of the libraries which is always painful.

**Comment by oerdnj** [comment]
It's building now, so should be fixed in about an hour (if everything goes well).

**Comment by oerdnj** [comment]
How does it look on your side now? I see that the amd64 packages should be ready now.

**Comment by fretb** [comment]
Still seeing issues I'm affraid, I noticed there are new packages (from today) in the apache2 directory,  but not in the other 2:

- https://packages.sury.org/apache2/pool/main/a/apr/
- https://packages.sury.org/apache2/pool/main/a/apr-util/

Maybe some more builds are needed?

```
       [2025-03-10T19:09:35+01:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: apt_package[libapache2-mod-security2] (apache::modsec line 3) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
       ---- Begin output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "libapache2-mod-security2=2.9.3-3+deb11u2"] ----
       STDOUT: Reading package lists...
       Building dependency tree...
       Reading state information...
       Some packages could not be installed. This may mean that you have
       requested an impossible situation or if you are using the unstable
       distribution that some required packages have not yet been created
       or been moved out of Incoming.
       The following information may help to resolve the situation:
       
       The following packages have unmet dependencies:
        libaprutil1t64 : Breaks: libaprutil1 (< 1.6.3-3+0~20250310.5+debian11~1.gbp0e3dab) but 1.6.3-1+0~20250308.1+debian11~1.gbpc0b512 is to be installed
       STDERR: E: Unable to correct problems, you have held broken packages.
       ---- End output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "libapache2-mod-security2=2.9.3-3+deb11u2"] ----
       Ran ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "libapache2-mod-security2=2.9.3-3+deb11u2"] returned 100
-----> Destroying <default-debian-11>...
```

**Comment by mishal** [comment]
```
$ sudo apt install libapache2-mod-security2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libaprutil1t64 : Breaks: libaprutil1 (< 1.6.3-3+0~20250310.5+debian11~1.gbp0e3dab) but 1.6.3-1+0~20250308.1+debian11~1.gbpc0b512 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by oerdnj** [comment]
Dog dammit, I made a copy & paste mistake. 🐻 with me for one more rebuild.

**Comment by mishal** [comment]
works now! thank you

**Comment by oerdnj** [comment]
I'm going to rebuild `src:apache2` once more just to be on the safe side.

**Comment by fretb** [comment]
Looks good on my end at this point as well. Thanks a bunch! Will have another test once you confirm the final rebuild.
