### ISSUE TITLE
PHP 7.0.3 FPM produces 502 Bad Gateway

### ISSUE THREAD

**Issue by thasmo** [oerdnj/deb.sury.org#247]
I'm encountering random `502 Bad Gateway` errors from Nginx, which are probably caused by PHP 7.0.3 FPM. The PHP error log shows the following, but I have no idea what it actually means or how it can be fixed. The Gateway error occurs pretty often but randomly. I've disabled all PHP modules, except mysqli, but the error persist.

```
[06-Feb-2016 21:16:09] NOTICE: fpm is running, pid 28379
[06-Feb-2016 21:16:09] NOTICE: ready to handle connections
[06-Feb-2016 21:16:09] NOTICE: systemd monitor interval set to 10000ms
[06-Feb-2016 21:17:52] WARNING: [pool www] child 28390 said into stderr: "*** Error in `php-fpm: pool www': corrupted double-linked list: 0x0000000002055d00 ***"
[06-Feb-2016 21:17:52] WARNING: [pool www] child 28390 exited on signal 6 (SIGABRT) after 103.610401 seconds from start
[06-Feb-2016 21:17:52] NOTICE: [pool www] child 28413 started
[06-Feb-2016 21:22:22] WARNING: [pool www] child 28383 said into stderr: "*** Error in `php-fpm: pool www': free(): invalid size: 0x000000000208bf30 ***"
[06-Feb-2016 21:22:22] WARNING: [pool www] child 28383 exited on signal 6 (SIGABRT) after 373.582334 seconds from start
[06-Feb-2016 21:22:22] NOTICE: [pool www] child 28415 started
[06-Feb-2016 21:22:23] WARNING: [pool www] child 28384 said into stderr: "*** Error in `php-fpm: pool www': free(): invalid size: 0x00000000020af690 ***"
[06-Feb-2016 21:22:23] WARNING: [pool www] child 28384 exited on signal 6 (SIGABRT) after 373.921252 seconds from start
[06-Feb-2016 21:22:23] NOTICE: [pool www] child 28416 started
[06-Feb-2016 21:23:33] WARNING: [pool www] child 28413 said into stderr: "*** Error in `php-fpm: pool www': munmap_chunk(): invalid pointer: 0x0000000002096940 ***"
[06-Feb-2016 21:23:33] WARNING: [pool www] child 28413 exited on signal 6 (SIGABRT) after 340.021992 seconds from start
[06-Feb-2016 21:23:33] NOTICE: [pool www] child 28418 started
[06-Feb-2016 21:23:35] WARNING: [pool www] child 28389 said into stderr: "*** Error in `php-fpm: pool www': free(): invalid size: 0x000000000207d8d0 ***"
[06-Feb-2016 21:23:35] WARNING: [pool www] child 28389 exited on signal 6 (SIGABRT) after 445.999018 seconds from start
[06-Feb-2016 21:23:35] NOTICE: [pool www] child 28419 started
[06-Feb-2016 21:23:37] WARNING: [pool www] child 28385 said into stderr: "*** Error in `php-fpm: pool www': munmap_chunk(): invalid pointer: 0x00000000020acf30 ***"
[06-Feb-2016 21:23:37] WARNING: [pool www] child 28385 exited on signal 6 (SIGABRT) after 448.212837 seconds from start
[06-Feb-2016 21:23:37] NOTICE: [pool www] child 28420 started
[06-Feb-2016 21:23:39] WARNING: [pool www] child 28416 said into stderr: "*** Error in `php-fpm: pool www': corrupted double-linked list: 0x0000000002065b60 ***"
[06-Feb-2016 21:23:39] WARNING: [pool www] child 28416 exited on signal 6 (SIGABRT) after 76.166465 seconds from start
[06-Feb-2016 21:23:39] NOTICE: [pool www] child 28421 started
[06-Feb-2016 21:23:41] WARNING: [pool www] child 28381 said into stderr: "*** Error in `php-fpm: pool www': corrupted double-linked list: 0x0000000002093df0 ***"
[06-Feb-2016 21:23:41] WARNING: [pool www] child 28381 exited on signal 6 (SIGABRT) after 452.127824 seconds from start
[06-Feb-2016 21:23:41] NOTICE: [pool www] child 28422 started
[06-Feb-2016 21:23:42] WARNING: [pool www] child 28418 said into stderr: "*** Error in `php-fpm: pool www': malloc(): smallbin double linked list corrupted: 0x00000000020820c0 ***"
[06-Feb-2016 21:23:42] WARNING: [pool www] child 28418 exited on signal 6 (SIGABRT) after 9.080129 seconds from start
[06-Feb-2016 21:23:42] NOTICE: [pool www] child 28423 started
[06-Feb-2016 21:23:43] WARNING: [pool www] child 28382 said into stderr: "*** Error in `php-fpm: pool www': free(): invalid size: 0x0000000002094e00 ***"
[06-Feb-2016 21:23:43] WARNING: [pool www] child 28382 exited on signal 6 (SIGABRT) after 454.518192 seconds from start
[06-Feb-2016 21:23:43] NOTICE: [pool www] child 28424 started
[06-Feb-2016 21:23:45] WARNING: [pool www] child 28419 said into stderr: "*** Error in `php-fpm: pool www': malloc(): smallbin double linked list corrupted: 0x00000000020820c0 ***"
[06-Feb-2016 21:23:45] WARNING: [pool www] child 28419 exited on signal 6 (SIGABRT) after 10.289139 seconds from start
[06-Feb-2016 21:23:45] NOTICE: [pool www] child 28425 started
[06-Feb-2016 21:23:49] WARNING: [pool www] child 28420 said into stderr: "*** Error in `php-fpm: pool www': malloc(): smallbin double linked list corrupted: 0x00000000020820e0 ***"
[06-Feb-2016 21:23:49] WARNING: [pool www] child 28420 exited on signal 6 (SIGABRT) after 11.762530 seconds from start
[06-Feb-2016 21:23:49] NOTICE: [pool www] child 28426 started
```

I'm running PHP `7.0.3-1+deb.sury.org~vivid+1` on Ubuntu 15.04: `Linux box 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by oerdnj** [comment]
Looks like an error in PHP itself. There's a quite long list of crashes fixed in upcoming 7.0.4: http://git.php.net/?p=php-src.git;a=blob;f=NEWS;h=a1854d03bbf2ef59e3de9df2e6b19ff092741c3b;hb=refs/heads/PHP-7.0

So I would suggest just be patient and report that to upstream if 7.0.4 doesn't help you.

**Comment by oerdnj** [comment]
@thasmo If you can, you can try 7.0.4RC1 available from `ppa:ondrej/php-qa`, perhaps it's already fixed in 7.0.4.

**Comment by thasmo** [comment]
@oerdnj Thanks, I'll try soonish! :)

**Comment by TazeTSchnitzel** [comment]
I think I have this issue (sorry for having emailed you, Ondrej, I should have come here first). Unfortunately, using the RC from php-qa doesn't fix it.

**Comment by oerdnj** [comment]
@thasmo @TazeTSchnitzel PHP 7.0.4 just came out, and it will be in the repository later this week. If you will be still able to reproduce the error, it needs to be reported as an upstream bug to https://bugs.php.net/how-to-report.php

**Comment by TazeTSchnitzel** [comment]
I upgraded to `7.0.4-1+deb.sury.org~trusty+1` and it's still broken. I'll report it.

**Comment by TazeTSchnitzel** [comment]
Issue I was getting only happened when I had `ext/mysql` loaded, interestingly. My code doesn't touch it.

**Comment by oerdnj** [comment]
@TazeTSchnitzel Could you report the upstream bug here, when you report it there? Thanks.

**Comment by TazeTSchnitzel** [comment]
I might eventually investigate the crash dump, but I decided to simply compile PHP 5.6 myself (with `ext/mysql` included) for the site that needs it. Everything else is using your PHP 7.0 without `ext/mysql` loaded.

**Comment by oerdnj** [comment]
You could've just installed php5.6-fpm and php5.6-mysql from the same repository...

**Comment by TazeTSchnitzel** [comment]
I tried that, but it lacks `ext/mysql` so far as I can see and SMF doesn't seem to like it.

**Comment by oerdnj** [comment]
@TazeTSchnitzel Ah, right, I unified the builds and the old plain mysql extension has been removed from PHP 7.0, so I am not building it for PHP 5.6 as well.

**Comment by equa2k9** [comment]
I have the same issue
`
2016/03/18 18:10:27 [error] 16213#16213: *6 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: botrend, request: "GET /?post_type=commercial&p=640 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "botrend"`
`
2016/03/18 18:24:47 [error] 16213#16213: *56 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: botrend, request: "GET /?post_type=commercial&p=640 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "botrend"
`

pages with uri like   >>>  botrend/new-post/   working some times normal, some times them not loaded too.

**Comment by thasmo** [comment]
@oerdnj, I've removed `php7.0-mysql` and now PHP seems to run stable. Unfortunately my application needs `mysqli` which is provided by the `php7.0-mysql` package. Is there a known solution or a workaround for this problem?

**Comment by oerdnj** [comment]
@TazeTSchnitzel @thasmo The issue would need backtrace, here's how to install debugging symbols: https://github.com/oerdnj/deb.sury.org/wiki/Debugging-symbols and you'll need to run fpm either under gdb (and wait for crash) or at least produce coredump (and produce backtrace).

**Comment by thasmo** [comment]
I've updated the file to this:
````
deb http://ppa.launchpad.net/ondrej/mysql-5.6/ubuntu wily main
deb http://ppa.launchpad.net/ondrej/mysql-5.6/ubuntu wily main/debug
# deb-src http://ppa.launchpad.net/ondrej/mysql-5.6/ubuntu wily main
```

When running `apt-get update` it says:
```
W: Failed to fetch http://ppa.launchpad.net/ondrej/mysql-5.6/ubuntu/dists/wily/InRelease  Unable to find expected entry 'main/debug/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

There's also no valid package:
```
E: Couldn't find any package by regex 'php7.0-mysql-dbgsym'
```

I guess I'm doing something wrong. Any idea what it may be?

**Comment by oerdnj** [comment]
@thasmo You enabled debug in mysql ppa, not in PHP one.

**Comment by thasmo** [comment]
Argh, thanks. On it. :)

**Comment by thasmo** [comment]
@oerdnj, it doesn't show any suspicious output, I guess:
```
(gdb) run -t
Starting program: /usr/sbin/php-fpm7.0 -t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[19-Mar-2016 14:15:52] NOTICE: configuration file /etc/php/7.0/fpm/php-fpm.conf test is successful
[Inferior 1 (process 3144) exited normally]
```

I waited for the `502 Bad Gateway` to happen and then ran `run -t`.

**Comment by oerdnj** [comment]
Nah, stop the service and do:
```
gdb /usr/sbin/php-fpm7.0
run --nodaemonize
```
After it crashes issue these commands  in gdb:
```
bt full
```

or even

```
thread apply all bt full
```

Also here are the instructions how to get a core dump: https://bugs.php.net/bugs-generating-backtrace.php

E.g. run:
```
mkdir -m 777 /tmp/php-fpm7.0
cd /tmp/php-fpm7.0
ulimit -c unlimited
php-fpm7.0 --nodaemonize
```

and then collect the coredump in the `/tmp/php-fpm7.0` directory (hopefully). If it's not there it might be elsewhere where FPM changedir to.

**Comment by thasmo** [comment]
Thanks, the output of `bt full` is:
```
#0  0x00007ffff60e5483 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x000055555584cad3 in fpm_event_epoll_wait (queue=<optimized out>, timeout=1000) at /build/php7.0-O39eri/php7.0-7.0.4/sapi/fpm/fpm/events/epoll.c:128
        ret = <optimized out>
        i = <optimized out>
        __func__ = "fpm_event_epoll_wait"
#2  0x00005555558430ec in fpm_event_loop (err=err@entry=0) at /build/php7.0-O39eri/php7.0-7.0.4/sapi/fpm/fpm/fpm_events.c:416
        q = <optimized out>
        ms = <optimized out>
        tmp = <optimized out>
        timeout = <optimized out>
        ret = <optimized out>
        q2 = <optimized out>
        now = {tv_sec = 261, tv_usec = 939969}
        signal_fd_event = {fd = 6, timeout = {tv_sec = 0, tv_usec = 0}, frequency = {tv_sec = 0, tv_usec = 0}, callback = 0x5555558425a0 <fpm_got_signal>, arg = 0x0, flags = 2, index = 6, which = 2}
        __func__ = "fpm_event_loop"
#3  0x000055555583d8a7 in fpm_run (max_requests=0x7fffffffe04c) at /build/php7.0-O39eri/php7.0-7.0.4/sapi/fpm/fpm/fpm.c:115
        wp = 0x0
#4  0x000055555562f34b in main (argc=2, argv=0x7fffffffe668) at /build/php7.0-O39eri/php7.0-7.0.4/sapi/fpm/fpm/fpm_main.c:1882
        exit_status = 0
        c = -1
        use_extended_info = 0
        file_handle = {handle = {fd = -134832128, fp = 0x7ffff7f6a000, stream = {handle = 0x7ffff7f6a000, isatty = -167895760, mmap = {len = 140737320512968, pos = 140737351923714, map = 0x8a5, buf = 0x7ffff5feedc8 "", old_handle = 0x7ffff7f6a000,
                old_closer = 0x7fffffffe1d8}, reader = 0x7fffffffe1d4, fsizer = 0x7ffff7de3190 <do_lookup_x+352>, closer = 0x1}}, filename = 0x7ffff7dd977c "free", opened_path = 0x7ffff7dd9420, type = 4294959576, free_filename = 255 '▒'}
        orig_optind = 1
        orig_optarg = 0x0
        ini_entries_len = 0
        max_requests = 500
        requests = 0
        fcgi_fd = 0
        request = <optimized out>
        fpm_config = 0x0
        fpm_prefix = 0x0
        fpm_pid = 0x0
        test_conf = 0
        force_daemon = 0
        force_stderr = 0
        php_information = 0
        php_allow_to_run_as_root = 0
        __func__ = "main"
```

**Comment by oerdnj** [comment]
This looks normal, perhaps it crashed in some other thread? Could you do the `thread apply all bt full`? Is there a single page that crashes FPM or is that just random?

**Comment by thasmo** [comment]
`thread apply all bt full` looks identical. It's crashing randomly, not on a single page/script. I'll do it once more, on a clean install - not sure I installed everything correctly.

**Comment by thasmo** [comment]
I've setup a new VM using the newly compiled 7.0.5 PHP PPA and `thread apply all bt full` still returns the same. When I run `php-fpm7.0 --nodaemonize` and the "Bad Gateway" occurs, I get this messages in the console:
```sh
*** Error in `php-fpm: pool www': munmap_chunk(): invalid pointer: 0x0000556f07f8a080 ***
[31-Mar-2016 20:49:21] WARNING: [pool www] child 17172 exited on signal 6 (SIGABRT) after 11.722263 seconds from start
[31-Mar-2016 20:49:21] NOTICE: [pool www] child 17173 started
```
But unfortunately I can't find a/the core-dump. Is it a normal file? How would it be called? Thanks!

**Comment by thasmo** [comment]
@oerdnj, I managed to get a coredump. Seems to be a binary file. What's next? :sweat_smile:

**Comment by oerdnj** [comment]
@thasmo try running `gdb /usr/sbin/php-fpm7.0` and issue `run --nodaemonize` and after it crashes issue `thread apply all bt full`.

Do you have dbgsym packages installed? https://github.com/oerdnj/deb.sury.org/wiki/Debugging-symbols

**Comment by thasmo** [comment]
Done, but it only prints the same as what I've already posted. Yes I've removed all PHP packages and reinstalled using `apt-get install php7.0-fpm-dbgsym php7.0-mysql-dbgsym`.
```sh
(gdb) thread apply all bt full

Thread 1 (Thread 0x7ffff7f627c0 (LWP 1941)):
#0  0x00007ffff60e4483 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x000055555584e0a3 in fpm_event_epoll_wait (queue=<optimized out>, timeout=1000) at /build/php7.0-9ZmHhj/php7.0-7.0.5/sapi/fpm/fpm/events/epoll.c:128
        ret = <optimized out>
        i = <optimized out>
        __func__ = "fpm_event_epoll_wait"
#2  0x00005555558446bc in fpm_event_loop (err=err@entry=0) at /build/php7.0-9ZmHhj/php7.0-7.0.5/sapi/fpm/fpm/fpm_events.c:416
        q = <optimized out>
        ms = <optimized out>
        tmp = <optimized out>
        timeout = <optimized out>
        ret = <optimized out>
        q2 = <optimized out>
        now = {tv_sec = 396, tv_usec = 612156}
        signal_fd_event = {fd = 5, timeout = {tv_sec = 0, tv_usec = 0}, frequency = {tv_sec = 0, tv_usec = 0}, callback = 0x555555843b70 <fpm_got_signal>, arg = 0x0, flags = 2, index = 5, which = 2}
        __func__ = "fpm_event_loop"
#3  0x000055555583ee77 in fpm_run (max_requests=0x7fffffffe04c) at /build/php7.0-9ZmHhj/php7.0-7.0.5/sapi/fpm/fpm/fpm.c:115
        wp = 0x0
#4  0x000055555562f38b in main (argc=2, argv=0x7fffffffe668) at /build/php7.0-9ZmHhj/php7.0-7.0.5/sapi/fpm/fpm/fpm_main.c:1882
        exit_status = 0
        c = -1
        use_extended_info = 0
        file_handle = {handle = {fd = -134832128, fp = 0x7ffff7f6a000, stream = {handle = 0x7ffff7f6a000, isatty = -167899856, mmap = {len = 140737320508872, pos = 140737351923714, map = 0x8a5, buf = 0x7ffff5feddc8 "", old_handle = 0x7ffff7f6a000,
                old_closer = 0x7fffffffe1d8}, reader = 0x7fffffffe1d4, fsizer = 0x7ffff7de3190 <do_lookup_x+352>, closer = 0x1}}, filename = 0x7ffff7dd977c "free", opened_path = 0x7ffff7dd9420, type = 4294959576, free_filename = 255 '▒'}
        orig_optind = 1
        orig_optarg = 0x0
        ini_entries_len = 0
        max_requests = 500
        requests = 0
        fcgi_fd = 0
        request = <optimized out>
        fpm_config = 0x0
        fpm_prefix = 0x0
        fpm_pid = 0x0
        test_conf = 0
        force_daemon = 0
        force_stderr = 0
        php_information = 0
        php_allow_to_run_as_root = 0
        __func__ = "main"
```

**Comment by oerdnj** [comment]
Could you also attach the lines after `run ...` and before running 'thread apply ...`, so the actual crash is documented?

**Comment by thasmo** [comment]
Ye, it says it has been dumped, @oerdnj:
```sh
`(gdb) run --nodaemonize
Starting program: /usr/sbin/php-fpm7.0 --nodaemonize
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[31-Mar-2016 21:10:24] NOTICE: fpm is running, pid 1941
[31-Mar-2016 21:10:24] NOTICE: ready to handle connections
[31-Mar-2016 21:10:24] NOTICE: systemd monitor interval set to 10000ms
*** Error in `php-fpm: pool www': free(): invalid pointer: 0x00007ffff7ee5706 ***
[31-Mar-2016 21:10:37] WARNING: [pool www] child 1945 exited on signal 6 (SIGABRT - core dumped) after 12.716053 seconds from start
[31-Mar-2016 21:10:37] NOTICE: [pool www] child 1947 started
```
To enable the coredump I followed [this guide](https://ma.ttias.be/generate-php-core-dumps-segfaults-php-fpm/), using `echo '/tmp/coredump-%e.%p' > /proc/sys/kernel/core_pattern`.

**Comment by equa2k9** [comment]
In my issue, i found a redirect loop in my code like:
from template `partials/features-items` i call `get_template_part('partials/post-time)`
and from `post-time` i also call `get_template_part('partials/features-items)` 
and this is produce to me 502error
Maybe for someone will be usefull

**Comment by oerdnj** [comment]
@equa2k9 yeah, that usually crashes PHP, you might have luck with xdebug: http://stackoverflow.com/questions/7327393/why-does-an-infinitely-recursive-function-in-php-cause-a-segfault

**Comment by oerdnj** [comment]
@thasmo Do you still experience reproducible crashes? And did you report this to upstream?

**Comment by thasmo** [comment]
Hey @oerdnj! Actually I've upgraded to Ubuntu 16.04 and use the PHP 7 version which comes with it without problems. And after all, I'm a bit lost regarding debugging this.

**Comment by oerdnj** [comment]
I am closing this bug then.
