### ISSUE TITLE
PHP7.1 xdebug not available

### ISSUE THREAD

**Issue by BlackIkeEagle** [oerdnj/deb.sury.org#496]
We wanted to start testing our codebase with PHP7.1, but xdebug is not available (there is no *.so)

**Comment by oerdnj** [comment]
Done, 2.5.0~rc1 has PHP 7.1 support.

**Comment by BlackIkeEagle** [comment]
thanks

**Comment by MatthiasKuehneEllerhold** [comment]
I still cant seem to install xDebug:
```
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y php7.1-xdebug
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 https://packages.sury.org jessie InRelease [6856 B]
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [421 kB]
Ign http://deb.debian.org jessie InRelease
Get:4 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:5 http://deb.debian.org jessie Release.gpg [2373 B]
Get:6 https://packages.sury.org jessie/main amd64 Packages [47.2 kB]
Get:7 http://deb.debian.org jessie Release [148 kB]
Get:8 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9915 kB in 6s (1431 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.1-xdebug
E: Couldn't find any package by regex 'php7.1-xdebug'
```

Although xDebug 2.5.0 for PHP 7.1 is out: https://xdebug.org/index.php

How did you manage to install it?

**Comment by kbond** [comment]
install the package `php-xdebug` - it provides xdebug for php5.6/7.0/7.1

**Comment by MatthiasKuehneEllerhold** [comment]
This installs php7.0 on top of it:
```
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y php-xdebug
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 https://packages.sury.org jessie InRelease [6856 B]
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [421 kB]
Ign http://deb.debian.org jessie InRelease
Get:4 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:5 http://deb.debian.org jessie Release.gpg [2373 B]
Get:6 https://packages.sury.org jessie/main amd64 Packages [47.2 kB]
Get:7 http://deb.debian.org jessie Release [148 kB]
Get:8 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9915 kB in 6s (1550 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-phpdbg
  php7.0-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php-xdebug php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-phpdbg
  php7.0-readline
0 upgraded, 7 newly installed, 0 to remove and 4 not upgraded.
Need to get 4241 kB of archives.
After this operation, 17.3 MB of additional disk space will be used.
Get:1 https://packages.sury.org/php/ jessie/main php7.0-common amd64 7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c [879 kB]
Get:2 https://packages.sury.org/php/ jessie/main php7.0-json amd64 7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c [17.4 kB]
Get:3 https://packages.sury.org/php/ jessie/main php7.0-opcache amd64 7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c [77.0 kB]
Get:4 https://packages.sury.org/php/ jessie/main php7.0-readline amd64 7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c [12.5 kB]
Get:5 https://packages.sury.org/php/ jessie/main php7.0-cli amd64 7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c [1285 kB]
Get:6 https://packages.sury.org/php/ jessie/main php7.0-phpdbg amd64 7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c [1325 kB]
Get:7 https://packages.sury.org/php/ jessie/main php-xdebug amd64 2.4.1-2+0~20161021113725.5+jessie~1.gbpa1fa0f [645 kB]
```
(Aborted)

**Comment by kbond** [comment]
try `apt-get install --no-install-recommends php-xdebug`

**Comment by MatthiasKuehneEllerhold** [comment]
Same:
```
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y php-xdebug -s
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 https://packages.sury.org jessie InRelease [6856 B]
Ign http://deb.debian.org jessie InRelease
Get:3 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:4 http://deb.debian.org jessie Release.gpg [2373 B]
Get:5 http://deb.debian.org jessie Release [148 kB]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [421 kB]
Get:7 https://packages.sury.org jessie/main amd64 Packages [47.2 kB]
Get:8 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9915 kB in 8s (1146 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-phpdbg
  php7.0-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php-xdebug php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-phpdbg
  php7.0-readline
0 upgraded, 7 newly installed, 0 to remove and 4 not upgraded.
Inst php7.0-common (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Inst php7.0-json (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Inst php7.0-opcache (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Inst php7.0-readline (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Inst php7.0-cli (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Inst php7.0-phpdbg (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Inst php-xdebug (2.4.1-2+0~20161021113725.5+jessie~1.gbpa1fa0f packages.sury.org [amd64])
Conf php7.0-common (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Conf php7.0-json (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Conf php7.0-opcache (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Conf php7.0-readline (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Conf php7.0-cli (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Conf php7.0-phpdbg (7.0.13-2+0~20161205110121.16+jessie~1.gbp259d9c packages.sury.org [amd64])
Conf php-xdebug (2.4.1-2+0~20161021113725.5+jessie~1.gbpa1fa0f packages.sury.org [amd64])
```

As you can see he wants to install "php-xdebug (2.4.1-2+0~20161021113725.5+jessie~1)" instead of the 2.5.0 (RC?).

**Comment by kbond** [comment]
hmm, I'm not sure. Just realized you are installing on Debian - I only have experience installing on Ubuntu.

**Comment by MatthiasKuehneEllerhold** [comment]
Ups, yeah I'm sorry. Im trying to install php7.1 on a debian jessie docker container.

**Comment by oerdnj** [comment]
I am currently fighting with MariaDB switch as default MySQL server, so it will be available when I resolve that.

**Comment by MatthiasKuehneEllerhold** [comment]
I thought @BlackIkeEagle got it working and wanted to know how.

OK, good luck with your MariaDB fight.

**Comment by BlackIkeEagle** [comment]
@MatthiasKuehneEllerhold just install php-xdebug, it will be available for your php version then.

I did not see php7.0 packages being pulled in. But I'm installing on ubuntu.

**Comment by MatthiasKuehneEllerhold** [comment]
See my exchange with @kbond above. It WILL install php7.0 and xdebug 2.4.1 (instead of 2.5.0+) on Debian Jessie.

**Comment by oerdnj** [comment]
Now reprepro was broken with newer dpkg on Debian stretch - failing all builds :(. Should be hopefully fixed now, and I have launched php5.6, php7.0 and php7.1 rebuild. Will take a while though...

**Comment by MatthiasKuehneEllerhold** [comment]
It works! Thanks @oerdnj !
The installed version is `php-xdebug (2.5.0-1+0~20161206202434.8+jessie~1.gbpd8b91d)`

**Comment by oerdnj** [comment]
Ok, now all should be good with a notable exception of PHP 5.6 on stretch that's broken because of OpenSSL 1.1.0 transition that happened in Debian stretch.

**Comment by gitowiec** [comment]
I don't know why I can't install xdebug for docker jessie image, I tried `php-xdebug` and `php7.1-xdebug`. It ended with this errors in sequence:

```
jessie
converted 'https://packages.sury.org/php/apt.gpg' (ANSI_X3.4-1968) -> 'https://packages.sury.org/php/apt.gpg' (UTF-8)
--2018-01-13 14:42:19--  https://packages.sury.org/php/apt.gpg
Resolving packages.sury.org (packages.sury.org)... 217.31.192.150, 2001:1488:ac15:ff90::150
Connecting to packages.sury.org (packages.sury.org)|217.31.192.150|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2239 (2.2K) [application/octet-stream]
Saving to: '/etc/apt/trusted.gpg.d/php.gpg'

     0K ..                                                    100% 24.2M=0s

2018-01-13 14:42:19 (24.2 MB/s) - '/etc/apt/trusted.gpg.d/php.gpg' saved [2239/2239]

Hit http://security.debian.org jessie/updates InRelease
Get:1 https://packages.sury.org jessie InRelease [6915 B]
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [605 kB]
Get:3 https://packages.sury.org jessie/main amd64 Packages [91.6 kB]
Get:4 http://deb.debian.org jessie-updates/main amd64 Packages [23.1 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9791 kB in 6s (1468 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package php-xdebug is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php-xdebug' has no installation candidate
```

```
jessie
converted 'https://packages.sury.org/php/apt.gpg' (ANSI_X3.4-1968) -> 'https://packages.sury.org/php/apt.gpg' (UTF-8)
--2018-01-13 14:35:05--  https://packages.sury.org/php/apt.gpg
Resolving packages.sury.org (packages.sury.org)... 217.31.192.150, 2001:1488:ac15:ff90::150
Connecting to packages.sury.org (packages.sury.org)|217.31.192.150|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2239 (2.2K) [application/octet-stream]
Saving to: '/etc/apt/trusted.gpg.d/php.gpg'

     0K ..                                                    100% 28.7M=0s

2018-01-13 14:35:06 (28.7 MB/s) - '/etc/apt/trusted.gpg.d/php.gpg' saved [2239/2239]

Hit http://security.debian.org jessie/updates InRelease
Get:1 https://packages.sury.org jessie InRelease [6915 B]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [605 kB]
Ign http://deb.debian.org jessie InRelease
Get:3 https://packages.sury.org jessie/main amd64 Packages [91.6 kB]
Hit http://deb.debian.org jessie-updates InRelease
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:4 http://deb.debian.org jessie-updates/main amd64 Packages [23.1 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9791 kB in 6s (1443 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package php7.1-xdebug is a virtual package provided by:
  php-xdebug 2.5.5-1+0~20170628201550.1+jessie~1.gbp5a1f48 [Not candidate version]

E: Package 'php7.1-xdebug' has no installation candidate
```

Here is my Dockerfile:
```
FROM wordpress:php7.1
# FROM wordpress:latest

RUN apt-get update \
    && apt-get install -y apt-utils apt-transport-https lsb-release ca-certificates wget \
    && echo $(lsb_release -sc) \
    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list' \
    && apt-get update \
    && apt-get install --no-install-recommends -y sendmail php-common

# COPY ./php.ini /usr/local/etc/php/conf.d/php.ini
COPY ./prepare.sh /prepare.sh
RUN chmod +x /prepare.sh
ENV XDEBUG_PORT 9000


CMD /prepare.sh && apache2-foreground
```

Could You help me?

**Comment by MatthiasKuehneEllerhold** [comment]
This works for my stretch-slim images:
```
DEBIAN_FRONTEND=noninteractive apt-get install -y php7.1-xdebug
```
Which debian / ubuntu is the wordpress image based upon?

**Comment by gitowiec** [comment]
Hi, thanks for the replay,
Here it is `FROM wordpress:php7.1` by searching through Docker Store I managed to recognize php7.1 image made from Debian Jessie. I would go with 7.2 which is based on Stretch but the XDebug for PHP 7.2 is still beta and I can't afford to stumble upon bugs not related to WordPress or PHP code.

**Comment by MatthiasKuehneEllerhold** [comment]
The question is how PHP was installed in the wordpress image. If its installed via the package manager (using debians sources) than installing xDebug via apt-get SHOULD work (and works for me).
But if its compiled and built from source than you have to use the instructions given in the link above.

Is this the image your image is based upon: https://hub.docker.com/_/wordpress/ ? There is an entire section on "Adding additional libraries / extensions" which links back to the link "https://hub.docker.com/_/php/" I gave you earlier.
