### ISSUE TITLE
php-redis in stretch repo provides php7.0-redis and doesn't work with PHP 7.1

### ISSUE THREAD

**Issue by valouille** [oerdnj/deb.sury.org#568]
Hello,

I installed PHP 7.1 from the repository at sury.org from the Stretch branch, but I can't find a suitable version of php-redis for it. The package php-redis from sury.org is built for 7.0 :

```
Package: php-redis
Version: 3.1.1~rc2-1+0~20170118110426.8+stretch~1.gbp11e7ce
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Installed-Size: 477
Depends: php-igbinary, php-common (>= 1:7.0+33~), phpapi-20151012, libc6 (>= 2.14)
Suggests: redis-server
Provides: php7.0-redis
Homepage: http://pecl.php.net/package/redis
Priority: optional
Section: php
Filename: pool/main/p/php-redis/php-redis_3.1.1~rc2-1+0~20170118110426.8+stretch~1.gbp11e7ce_amd64.deb
Size: 113014
SHA256: 429c98a9ea19cdff1495b7bf59e54af2fa86a741ecc5769960ff2d94804d0516
SHA1: ae33d3a3716a330d42dc939953a91723df15a52c
MD5sum: 32423a840c9a834e126c5a01a6f5005c
Description-en: PHP extension for interfacing with Redis
 This extension allows php applications to communicate with the Redis
 persistent key-value store.  The php-redis module provides an easy
 object oriented interface.
Description-md5: b8a3de89cf7f4311899f1f5751dbc60a
```

Can you build a version that can be loaded using PHP 7.1 ?

Thank you

Valérian

**Comment by oerdnj** [comment]
Should be fixed now. The `php-defaults` in the repository was older than the one in stretch causing all extensions to be built just with PHP 7.0.

The new build shows:
```
Package: php-redis
Version: 3.1.1-1+0~20170315141536.10+stretch~1.gbpfefafe
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Installed-Size: 1432
Depends: php-igbinary, php-common (>= 1:7.0+33~), **phpapi-20160303 | phpapi-20151012 | phpapi-20131226**, libc6 (>= 2.14)
Suggests: redis-server
Provides: php5.6-redis, php7.0-redis, php7.1-redis
Homepage: http://pecl.php.net/package/redis
Priority: optional
Section: php
Filename: pool/main/p/php-redis/php-redis_3.1.1-1+0~20170315141536.10+stretch~1.gbpfefafe_amd64.deb
Size: 253652
SHA256: dc1159e113fd5117956ce45e2452b60224145977757e4576d3b93e18f1d8a1b4
SHA1: cade6b6727e2b96f24614e19921b97297a86c7aa
MD5sum: 4a4651b2d975edf163a99dd08bb84b3e
Description-en: PHP extension for interfacing with Redis
 This extension allows php applications to communicate with the Redis
 persistent key-value store.  The php-redis module provides an easy
 object oriented interface.
Description-md5: b8a3de89cf7f4311899f1f5751dbc60a
```

**Comment by weirdan** [comment]
Is this going to get into Debian/sid at some time? Apologies if I'm asking it in the wrong place.

**Comment by IceShack** [comment]
It seems like this error is back.
I'm trying to install php-redis for PHP 7.1 on Debian Stretch and it doesn't work.
Package info:
```
Package: php-redis
Version: 3.1.1-1
Installed-Size: 477
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Architecture: amd64
Provides: php7.0-redis
Depends: php-igbinary, php-common (>= 1:7.0+33~), phpapi-20151012, libc6 (>= 2.14)
Suggests: redis-server
Description-en: PHP extension for interfacing with Redis
 This extension allows php applications to communicate with the Redis
 persistent key-value store.  The php-redis module provides an easy
 object oriented interface.
Description-md5: b8a3de89cf7f4311899f1f5751dbc60a
Homepage: http://pecl.php.net/package/redis
Section: php
Priority: optional
Filename: pool/main/p/php-redis/php-redis_3.1.1-1_amd64.deb
Size: 112932
MD5sum: e6795bc3d1195c8786974a1cbbffadaf
SHA256: 021a5e480c30e3aa0e315d88dbb2577fb41fd3e5306e9e7bc0e13f1b2b5736a3
```
