### ISSUE TITLE
php-fpm7.2: symbol lookup error: php-fpm7.2: undefined symbol: pcre_jit_exec

### ISSUE THREAD

**Issue by mauricemeyer** [oerdnj/deb.sury.org#755]
Hey,

as in #687, I can't seem to start PHP7.2-fpm on Ubuntu 14.04. 

```
root@hostname:/# php-fpm7.2
php-fpm7.2: symbol lookup error: php-fpm7.2: undefined symbol: pcre_jit_exec
```

I added the output of the commands from the other tickets below:

```
root@hostname:/# php 7.2 --version
php: symbol lookup error: php: undefined symbol: pcre_jit_exec
root@hostname:/# which php7.2
/usr/bin/php7.2
root@hostname:/# ldd $(which php7.2)
        linux-vdso.so.1 =>  (0x00007ffd32b43000)
        libargon2.so.0 => /usr/lib/x86_64-linux-gnu/libargon2.so.0 (0x00007f64a436a000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f64a414f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f64a3f36000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f64a3cf8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f64a39f2000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f64a37ee000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f64a3488000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f64a321e000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f64a2da8000)
        libsodium.so.18 => /usr/lib/x86_64-linux-gnu/libsodium.so.18 (0x00007f64a2b38000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f64a276f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f64a2551000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f64a4c19000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f64a232f000)
root@hostname:/# apt-cache policy php7.2-cli
php7.2-cli:
  Installed: 7.2.0-1+ubuntu14.04.1+deb.sury.org+1
  Candidate: 7.2.0-1+ubuntu14.04.1+deb.sury.org+1
  Version table:
 *** 7.2.0-1+ubuntu14.04.1+deb.sury.org+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

Is this a known issue?

**Comment by todeveni** [comment]
What about `apt-cache policy libpcre3` output?

If the "Installed" row doesn't have `deb.sury.org` package in it, try installing/upgrading libpcre3 `apt-get install libpcre3`

**Comment by mauricemeyer** [comment]
Thanks for that hint, that indeed fixed it.

I had `2:8.38-3.1` installed, update installed version `2:8.41-1.1+ubuntu16.04.1+deb.sury.org+3`.

But this tells me that the dependencies are not set correctly for `php7.2-fmp` as it currently depends on `libpcre3 (>= 1:8.20)`. 

@oerdnj Could you please fix the dependencies for `php7.2-fpm` to fix this?

Thanks a lot!

**Comment by oerdnj** [comment]
I bumped the minimal version for pcre_jit_exec to 8.41, so it will get fixed in the next PHP rebuilds. But generally, full `apt-get update && apt-get dist-upgrade` is needed before filling a bug report.

**Comment by mauricemeyer** [comment]
@oerdnj I agree with system updates before filing a bug report - but only to be more exact about what causes the bug.

Nevertheless should packages come with correct dependencies as the installation of a package should not require a `dist-upgrade` afterwards to make it work.

Thanks for the quick reaction!

**Comment by mauricemeyer** [comment]
Sorry for bugging you again, but the latest rebuild didn't fix it, on `trusty`, `libpcre3 (>= 1:8.20)` is still the dependency. 

The update of `libpcre3` to `2:8.41-1.1+ubuntu14.04.1+deb.sury.org+3` fixed it as expected.

**Comment by oerdnj** [comment]
There are actually two flavors of pcre3 library related to gcc upgrade, and I only updated the more recent one. I have now updated both of them, so next rebuild should do the trick :)

**Comment by root360-AndreasUlm** [comment]
Hi,

As libpcre3 is already installed on e.g. Ubuntu you have to upgrade at least libpcre3 everytime you install php7.2 on a new system otherwise you can't use it.
An example output for Ubuntu14.04:
```
$ apt-cache show php7.2-fpm                                                                                                                          
Package: php7.2-fpm                                                                                                                                                                                                
Source: php7.2                                                                                                                                                                                                     
Priority: optional                                                                                                                                                                                                 
Section: php                                                                                                                                                                                                       
Installed-Size: 4804                                                                                                                                                                                               
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>                                                                                                                                         
Architecture: amd64                                                                                                                                                                                                
Version: 7.2.0~rc6-1+ubuntu14.04.1+deb.sury.org+1                                                                                                                                                                  
Suggests: php-pear                                                                                                                                                                                                 
Provides: php-fpm, phpapi-20170718                                                                                                                                                                                 
Depends: libmagic1, libpcre3 (>= 1:8.20), mime-support, php7.2-cli, php7.2-common (= 7.2.0~rc6-1+ubuntu14.04.1+deb.sury.org+1), php7.2-json, php7.2-opcache, tzdata, ucf, init-system-helpers (>= 1.13~), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), libapparmor1 (>= 2.7.0~beta1+bzr1772), libargon2-0 (>= 0~20160406~), libc6 (>= 2.15), libsodium18 (>= 1.0.14), libssl1.1 (>= 1.1.0), libsystemd-daemon0 (>= 31), libxml2 (>= 2.8.0), zlib1g (>= 1:1.1.4)                                                                                                                                                                                          
Filename: pool/main/p/php7.2/php7.2-fpm_7.2.0~rc6-1+ubuntu14.04.1+deb.sury.org+1_amd64.deb                                                                                                                         
Size: 1358586                                                                                                                                                                                                      
MD5sum: 30683e7c140c375f5d29a915080d4a79                                                                                                                                                                           
SHA1: 8cb301b1044158e9b923cd54e08a25da8452aa02                                                                                                                                                                     
SHA256: 3fb183c4f33fa6b93811a499db5d03bc66038cb87d9cd4ad05e2d9786f8ae592                                                                                                                                           
Description-en: server-side, HTML-embedded scripting language (FPM-CGI binary)                                                                                                                                     
 This package provides the Fast Process Manager interpreter that runs                                                                                                                                              
 as a daemon and receives Fast/CGI requests.  Note that MOST Apache users                                                                                                                                          
 probably want the libapache2-mod-php7.2 package.                                                                                                                                                                  
 .                                                                                                                                                                                                                 
 The following extensions are built in: Core date filter hash libxml openssl                                                                                                                                       
 pcre Reflection session sodium SPL standard zlib.                                                                                                                                                                 
 .                                                                                                                                                                                                                 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used                                                                                                                                          
 open source general-purpose scripting language that is especially suited                                                                                                                                          
 for web development and can be embedded into HTML.                                                                                                                                                                
Description-md5: 542b40cacbee93baaa98ebd0f607dc65

$ apt-cache policy libpcre3                                                                                                                          
libpcre3:                                                                                                                                                                                                          
  Installed: 1:8.31-2ubuntu2.3                                                                                                                                                                                     
  Candidate: 2:8.41-1.1+ubuntu14.04.1+deb.sury.org+3                                                                                                                                                               
  Version table:                                                                                                                                                                                                   
     2:8.41-1.1+ubuntu14.04.1+deb.sury.org+3 0                                                                                                                                                                     
        500 http://repo-ubuntu-eu-central-1-a.root360.cloud/ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages                                                                                        
 *** 1:8.31-2ubuntu2.3 0                                                                                                                                                                                           
        500 http://repo-ubuntu-eu-central-1-a.root360.cloud/archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages                                                                                          
        100 /var/lib/dpkg/status                                                                                                                                                                                   
     1:8.31-2ubuntu2.2 0                                                                                                                                                                                           
        500 http://repo-ubuntu-eu-central-1-a.root360.cloud/archive.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages                                                                                         
     1:8.31-2ubuntu2 0                                                                                                                                                                                             
        500 http://repo-ubuntu-eu-central-1-a.root360.cloud/archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

Wouldn't it be the best way to change the depends of the php7.2 packages to require libpcre3 >= 8.41?

By changing the depends you just have to activate your repository and install php7.2 which are the same steps you have to do to install php7.1.

Best regards,
Andreas
