### ISSUE TITLE
libcurl4 and php7.2-curl

### ISSUE THREAD

**Issue by svrin** [oerdnj/deb.sury.org#831]
Thx for your great work,

using ubuntu 18.04 in evaluation its currently impossible to install php7.2-curl and curl (because second depends on libcurl4, but first one seems to use libcurl3):

```
╰─$ sudo apt install curl php7.2-curl                                                                                                                                                                                                  130 ↵
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php7.2-curl is already the newest version (7.2.3-1+ubuntu18.04.1+deb.sury.org+1).
php7.2-curl set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 curl : Depends: libcurl4 (= 7.58.0-2ubuntu2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Can you provide for ubuntu bionic a php-curl version using libcurl4 please?

**Comment by jeroenvermeulen** [comment]
We have the same problem.
The deb.sury.org `php*-curl` packages depend on `libcurl4` while the default Ubuntu `curl` package (for commandline curl) depends on `libcurl3`. 
Of course we need it both installed at the same time.

**Comment by ser** [comment]
Yup, I can confirm, bionic version is useless at the moment.

**Comment by victormongi** [comment]
How to solve this? I got the same error... 
`php7.2-curl : Depends: libcurl3`

**Comment by victormongi** [comment]
Solved by running this `~$ apt-get upgrade
~$ apt-get install libcurl3`

**Comment by netcoop** [comment]
`apt-get install libcurl3` is not a good solution as it removes the servers curl package (a.o.):

`The following packages will be REMOVED:
  curl libcurl4 pollinate ubuntu-server
The following NEW packages will be installed:
  libcurl3
0 upgraded, 1 newly installed, 4 to remove and 0 not upgraded.`

**Comment by oerdnj** [comment]
I have just issued a rebuild for bionic packages that should fix it.

**Comment by netcoop** [comment]
Thanks, but I tried again after `apt-get update`, still the same issue.

`apt-cache showpkg php7.2-curl`
Gives me this:

`Dependencies: 
7.2.3-1+ubuntu18.04.1+deb.sury.org+1 - php-common (2 1:35) ucf (0 (null)) php7.2-common (5 7.2.3-1+ubuntu18.04.1+deb.sury.org+1) libc6 (2 2.14) libcurl3 (2 7.44.0) 
7.2.3-1ubuntu1 - php-common (2 1:35) ucf (0 (null)) php7.2-common (5 7.2.3-1ubuntu1) libc6 (2 2.14) libcurl4 (2 7.44.0) 
`

**Comment by oerdnj** [comment]
That just means that the build hasn’t finished yet.

**Comment by netcoop** [comment]
Ok, thanks. I'll try again a bit later.

**Comment by oerdnj** [comment]
lgtm now.

**Comment by victormongi** [comment]
@oerdnj I think this issue solved... Thank you....

**Comment by iget-master** [comment]
Same issue here on php7.2-curl on Bionic (sorry for the log in portuguese)

```
Os pacotes a seguir têm dependências desencontradas:
 php7.2-curl : Depende: libcurl3 (>= 7.44.0) mas não será instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.
```

**Comment by alienk1** [comment]
```
add-apt-repository ppa:ondrej/php
apt update
apt install php7.2-curl
```

**Comment by Dot-Rar** [comment]
Still having this issue on Stretch:
```
root@6ix9ine:/etc/apt/sources.list.d# apt install php7.2-curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.2-curl : Depends: libcurl3 (>= 7.44.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@6ix9ine:/etc/apt/sources.list.d# apt-cache depends php7.2-curl
php7.2-curl
  Depends: php-common
  Depends: ucf
  Depends: php7.2-common
  Depends: libc6
  Depends: libcurl3
```

**Comment by oerdnj** [comment]
What happena when you do:

apt-get install libcurl3

?

**Comment by Dot-Rar** [comment]
It installs, however it also removes curl, libcurl4 and gitlab-runner (which depends on libcurl4)

**Comment by oerdnj** [comment]
There’s no licurl4 in stretch
